input:
  one-wire:
    addresses:
      solar-in: 28-00ff9843111b
      solar-out: 28-000f9843076d
      thermo-fire-place: 28-000b984307bf
      boiler-up: 28-000f98431502
      boiler-middle: 28-001898430662
      boiler-low: 28-000b98430f0a
output:
  digital:
    pin:
      thermo-integration: 17
      solar-pump: 27
      thermo-valve: 22
      fan-coil-1: 23
      fan-coil-2: 24
      fan-coil-3: 25
      unused-1: 5
      unused-2: 6

spring:
  main:
    banner-mode: off

  redis:
    database: 0
    host: redis
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    timeout: 60000
