version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    ports:
      - "6379:6379"
    # --save 20 10 # persist data every 20 second if at least 10 write operation are performed
    command: |
      redis-server
      --save 20 10
      --loglevel warning
      --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./redis-data:/data

  solar:
    image: giangi/solar
    container_name: solar
    depends_on:
      - redis
    environment:
      JAVA_OPTS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "8080:8080"
    volumes:
      - "/sys/class/gpio:/sys/class/gpio:rw"
      - "/sys/bus/w1:/sys/bus/w1:r"